"use client";
import React, { useState } from "react";

const modalContent = {
  terms: {
    title: "Terms of Use",
    content: `Last Updated: May 2025

These Terms of Use ("Terms") govern your access to and use of TYME. By using the platform, you agree to be bound by these Terms.

1.1 Eligibility
You must be at least 18 years of age or the age of legal majority in your jurisdiction to use this platform.

1.2 License to Use
We grant you a non-exclusive, non-transferable, limited right to access and use TYME for your personal or internal business purposes, subject to these Terms.

You may not:

Copy, distribute, sublicense, or commercially exploit platform content without our express permission.
Use the platform in any manner that may harm, disable, overburden, or impair any of our services or systems.

1.3 User Responsibilities
You are solely responsible for:

Any content or inputs you provide to the platform.
Compliance with applicable laws in your jurisdiction.
Verifying the accuracy and appropriateness of AI-generated content before use.

1.4 Intellectual Property
All content, design elements, source code, and platform features are the intellectual property of TYME or its licensors and are protected under applicable copyright, trademark, and patent laws.

AI-generated content may be reused, modified, or published by you unless otherwise restricted, but TYME bears no responsibility for how that content is used.

1.5 Termination
We reserve the right to suspend or terminate your access to the platform at our sole discretion, without notice, if we believe you have violated these Terms or any applicable laws.

1.6 Disclaimers & Limitation of Liability
The platform is provided on an "AS IS" and "AS AVAILABLE" basis. We do not warrant:

That the platform will be error-free or uninterrupted.
That the outputs generated by the AI are accurate, suitable, or free from bias.
That any results or outcomes derived from using TYME will meet your expectations or needs.

To the fullest extent permitted by law, TYME disclaims all liability for any direct, indirect, incidental, or consequential damages arising from your use of the platform.

2. CHANGES TO THESE TERMS
We may revise our Disclaimer, Policies, and Terms of Use from time to time. We will post the updated version on this page, and your continued use of the platform constitutes your acceptance of the updated terms.

3. CONTACT INFORMATION
For questions, complaints, or legal inquiries, please contact us at:

Email: support@neuralarc.ai`
  },
  privacy: {
    title: "Privacy Policy",
    content: `Effective Date: May 2025

This Privacy Policy outlines how TYME ("we", "us", or "our") collects, processes, and protects your information when you use https://tyme-two.vercel.app ("the Platform").

1. Information We Collect
We may collect the following categories of data:

1.1 Personal Information (if provided): name, email address, contact details.
1.2 Usage Data: IP address, browser type, device type, session time, referring URLs, and interaction metrics.
1.3 User Inputs: Content, prompts, questions, or other inputs submitted to the AI system.
We do not intentionally collect sensitive personal data unless voluntarily provided.

2. How We Use Your Data
We use collected data to:

2.1 Provide, maintain, and improve the functionality of the platform.
2.2 Analyze user behavior for product enhancements.
2.3 Enforce legal terms and prevent misuse.
2.4 Communicate updates, features, and service-related announcements (if opted-in).

3. Third-Party Services
We may use third-party services (e.g., OpenAI, Vercel, Google Analytics) that help power our platform or analyze usage. These services may collect data independently under their own privacy policies.

4. Data Retention and Security
We retain your data only for as long as necessary to fulfill the purposes described above, or as required by law. We use commercially reasonable safeguards to protect your data but cannot guarantee absolute security.

5. Your Rights
You may request to access, update, or delete your data at any time by contacting us at support@neuralarc.ai. We will respond in accordance with applicable data protection laws.`
  },
  disclaimer: {
    title: "Disclaimer",
    content: `DISCLAIMER
Last updated: May 2025

TYME is a productivity platform powered by artificial intelligence (AI) technologies. The outputs generated by the system are algorithmically derived and may not always be accurate, complete, or appropriate for every situation.

By using TYME, you acknowledge and agree that:

The platform is not a substitute for professional advice (legal, medical, financial, or otherwise).
You are solely responsible for evaluating and verifying any outputs, insights, or recommendations generated by TYME.
TYME does not guarantee the accuracy, reliability, or correctness of any AI-generated content.
Under no circumstances shall TYME, its developers, affiliates, or licensors be held liable for any loss, damage, or harm resulting from your use of or reliance on any content generated through the platform.`
  },
  ai: {
    title: "Responsible AI Use Policy",
    content: `Responsible AI Use Policy
At TYME, we are committed to fostering the safe, ethical, and responsible use of artificial intelligence.

1. As a user, you agree that you will NOT:
- Use TYME to generate or disseminate content that is unlawful, offensive, discriminatory, violent, harassing, or misleading.
- Use the platform for any activity that violates applicable local, national, or international laws or regulations.
- Input any personal, confidential, or sensitive information into the system that could compromise your own or others' privacy.
- Attempt to manipulate or deceive the AI system into producing harmful or malicious outputs.
- Reverse engineer, reproduce, or attempt to replicate the platform's algorithms or source code.

2. We reserve the right to:
- Monitor user behavior for compliance with our ethical guidelines and applicable laws.
- Suspend or terminate access to the platform for violations of this policy.
- Report serious misuse to appropriate authorities or enforcement bodies where legally required.`
  }
};

function Modal({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: React.ReactNode }) {
  if (!open) return null;
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-2"
      onClick={e => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        className="bg-[#18181b] rounded-lg shadow-lg max-w-lg w-full p-6 relative overflow-y-auto"
        style={{ maxHeight: '80vh' }}
      >
        <button
          className="absolute top-3 right-3 text-gray-400 hover:text-white text-2xl"
          onClick={onClose}
          aria-label="Close"
        >
          ×
        </button>
        <h2 className="text-xl font-semibold mb-4 text-white">{title}</h2>
        <div className="text-gray-200 whitespace-pre-line">{children}</div>
      </div>
    </div>
  );
}

export function Footer() {
  const [modal, setModal] = useState<null | keyof typeof modalContent>(null);

  return (
    <footer className="w-full bg-black text-gray-300 py-4 px-2 border-t border-gray-800 flex items-center justify-center">
      <div className="flex flex-row flex-wrap items-center justify-center gap-3 text-sm w-full max-w-6xl">
        <button className="hover:underline" onClick={() => setModal("terms")}>Terms of use</button>
        <span className="mx-1">•</span>
        <button className="hover:underline" onClick={() => setModal("privacy")}>Privacy Policy</button>
        <span className="mx-1">•</span>
        <button className="hover:underline" onClick={() => setModal("disclaimer")}>Disclaimer</button>
        <span className="mx-1">•</span>
        <button className="hover:underline" onClick={() => setModal("ai")}>Responsible AI</button>
        <span className="mx-1">•</span>
         <span className="text-white/80">Copyright © 2025. All rights reserved.&nbsp;&nbsp;&nbsp;&nbsp;Tyme, a thing by{'  '}
          <a href="https://neuralarc.ai" target="_blank" rel="noopener noreferrer" className="inline-flex ml-1 items-center underline hover:text-white transition">
            Neural Arc
            <img src="/images/neural-footer.png" alt="Neural Arc Logo" style={{ height: 18 }} className="ml-2 inline-block align-middle" />
          </a>
        </span>
      </div>
      {/* Modal */}
      {modal && (
        <Modal
          open={!!modal}
          onClose={() => setModal(null)}
          title={modalContent[modal].title}
        >
          {modalContent[modal].content}
        </Modal>
      )}
    </footer>
  );
} 