export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white p-8">
      <div className="max-w-4xl mx-auto prose prose-lg">
        <h1>TERMS OF USE</h1>
        <p className="text-gray-600">Last Updated: May 2025</p>

        <p>These Terms of Use ("Terms") govern your access to and use of TYME. By using the platform, you agree to be bound by these Terms.</p>

        <h2>4.1 Eligibility</h2>
        <p>You must be at least 18 years of age or the age of legal majority in your jurisdiction to use this platform.</p>

        <h2>4.2 License to Use</h2>
        <p>We grant you a non-exclusive, non-transferable, limited right to access and use TYME for your personal or internal business purposes, subject to these Terms.</p>

        <p>You may not:</p>
        <ul>
          <li>Copy, distribute, sublicense, or commercially exploit platform content without our express permission.</li>
          <li>Use the platform in any manner that may harm, disable, overburden, or impair any of our services or systems.</li>
        </ul>

        <h2>4.3 User Responsibilities</h2>
        <p>You are solely responsible for:</p>
        <ul>
          <li>Any content or inputs you provide to the platform.</li>
          <li>Compliance with applicable laws in your jurisdiction.</li>
          <li>Verifying the accuracy and appropriateness of AI-generated content before use.</li>
        </ul>

        <h2>4.4 Intellectual Property</h2>
        <p>All content, design elements, source code, and platform features are the intellectual property of TYME or its licensors and are protected under applicable copyright, trademark, and patent laws.</p>

        <p>AI-generated content may be reused, modified, or published by you unless otherwise restricted, but TYME bears no responsibility for how that content is used.</p>

        <h2>4.5 Termination</h2>
        <p>We reserve the right to suspend or terminate your access to the platform at our sole discretion, without notice, if we believe you have violated these Terms or any applicable laws.</p>

        <h2>4.6 Disclaimers & Limitation of Liability</h2>
        <p>The platform is provided on an "AS IS" and "AS AVAILABLE" basis. We do not warrant:</p>
        <ul>
          <li>That the platform will be error-free or uninterrupted.</li>
          <li>That the outputs generated by the AI are accurate, suitable, or free from bias.</li>
          <li>That any results or outcomes derived from using TYME will meet your expectations or needs.</li>
        </ul>

        <p>To the fullest extent permitted by law, TYME disclaims all liability for any direct, indirect, incidental, or consequential damages arising from your use of the platform.</p>
      </div>
    </div>
  )
} 