export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white p-8">
      <div className="max-w-4xl mx-auto prose prose-lg">
        <h1>DISCLAIMER</h1>
        <p className="text-gray-600">Last updated: May 2025</p>

        <p>TYME is a productivity platform powered by artificial intelligence (AI) technologies. The outputs generated by the system are algorithmically derived and may not always be accurate, complete, or appropriate for every situation.</p>

        <p>By using TYME, you acknowledge and agree that:</p>

        <ul>
          <li>The platform is not a substitute for professional advice (legal, medical, financial, or otherwise).</li>
          <li>You are solely responsible for evaluating and verifying any outputs, insights, or recommendations generated by TYME.</li>
          <li>TYME does not guarantee the accuracy, reliability, or correctness of any AI-generated content.</li>
          <li>Under no circumstances shall TYME, its developers, affiliates, or licensors be held liable for any loss, damage, or harm resulting from your use of or reliance on any content generated through the platform.</li>
        </ul>
      </div>
    </div>
  )
} 